config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: :show
  resources :users, only: [:index, :show, :edit, :update] do
    resources :books, only: [:index, :show, :new, :create, :destroy] do
      resources :impressions, only: [:create, :destroy]
    end
    resources :storages, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :letters, only: [:index, :show, :create] do
    resources :comments, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  root 'letters#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :comments, ->{ order("updated_at desc") }, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, ->{ order("updated_at desc") }, through: :active_relationships, source: :following
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, ->{ order("updated_at desc") }, through: :passive_relationships, source: :follower
  has_many :storages, ->{ order("created_at desc")}
  has_many :books, ->{ order("created_at desc") }
  has_many :impressions

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def storage_letters
    letters = []

    self.storages.each do |storage|
      letters.push(storage.letter)
    end

    letters.reject(&:blank?)
  end

  def user_letters
    letters = []
    self.comments.each do |comment|
      letters << comment.letter
    end
    letters
  end

  def sum_like
    sum_likes = 0
    self.comments.each do |comment|
      sum_likes += comment.likes.length
    end
    sum_likes
  end

  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  def with_following(other_user)
    active_relationships.find_by(following_id: other_user.id)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def full_name
    "#{last_name} #{first_name}"
  end

  def self.select_or_create_omniauth(auth)
    find_by(auth.slice(:provider, :uid)) || self.create(
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email,
      first_name: auth.info.name.split[0],
      last_name: auth.info.name.split[1],
      password: Devise.friendly_token[0,20]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :set_user, except: :index

  def index
    @users = User.all
  end

  def show
    @letters = @user.user_letters
  end

  def edit
    if current_user != @user
      redirect_to root_path
    end
  end

  def update
    if current_user == @user
      if @user.update(update_params)
        flash[:notice] = "ユーザー情報の編集に成功しました。"
      else
        flash[:alert] = "ユーザー情報の編集に失敗しました。"
      end
      redirect_to :back
    else
      redirect_to root_path
    end
  end

  def following
    @follows = @user.following
  end

  def followers
    @follows = @user.followers
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def update_params
      params.require(:user).permit(:avatar, :last_name, :first_name, :profile)
    end
end

app/views/users/_follow.html.haml
.user-container__tab-contents
  .user-container__tab-contents__items
    - @follows.each do |follow|
      .user-container__tab-contents__items__user-info
        .user-container__tab-contents__items__user-info__upper-block
          = link_to user_path(follow) do
            = image_tag follow.avatar.presence || "default_avatar.jpeg", class: "user-container__tab-contents__items__user-info__upper-block__avatar"
          - if follow.full_name.present?
            = link_to follow.full_name.truncate(14), user_path(follow), class: "user-container__tab-contents__items__user-info__upper-block__name"
          - else
            = link_to "No name", user_path(follow), class: "user-container__tab-contents__items__user-info__upper-block__name"
        .user-container__tab-contents__items__user-info__lower-block
          =link_to following_user_path(follow), class: "user-container__tab-contents__items__user-info__lower-block__following" do
            .user-container__tab-contents__items__user-info__lower-block__following__caption
              %span フォロー
            .user-container__tab-contents__items__user-info__lower-block__following__count
              = follow.active_relationships.count
          =link_to followers_user_path(follow), class: "user-container__tab-contents__items__user-info__lower-block__follower" do
            .user-container__tab-contents__items__user-info__lower-block__follower__caption
              %span フォロワー
            .user-container__tab-contents__items__user-info__lower-block__follower__count
              = follow.passive_relationships.count
          .user-container__tab-contents__items__user-info__lower-block__follow
            - if follow == current_user
            - elsif current_user.following.include?(follow)
              = form_for current_user.with_following(follow), method: :delete do |f|
                = f.submit "フォロー中", class: "user-container__tab-contents__items__user-info__lower-block__follow__btn-blue"
            - else
              = form_tag '/relationships', method: :post do
                = hidden_field_tag :following_id, follow.id
                = submit_tag "フォロー", class: "user-container__tab-contents__items__user-info__lower-block__follow__btn"

app/views/users/_letter.html.haml
.user-container__letter-container__individual-letter
  .user-container__letter-container__individual-letter__thumbnail
    = link_to letter_path(letter) do
      = image_tag letter.image.presence || "default_letter_image.jpg", class: "user-container__letter-container__individual-letter__thumbnail__image"
      .user-container__letter-container__individual-letter__thumbnail__picks-box
        .user-container__letter-container__individual-letter__thumbnail__picks-box__cover
          .user-container__letter-container__individual-letter__thumbnail__picks-box__cover__size
            = letter.comments.length
          .user-container__letter-container__individual-letter__thumbnail__picks-box__cover__picks
            Picks
  .user-container__letter-container__individual-letter__title
    %h2
      = link_to letter.title.truncate(28).presence || "No title", letter_path(letter), class: "user-container__letter-container__individual-letter__title__font"
  .user-container__letter-container__individual-letter__user
    .user-container__letter-container__individual-letter__user__thumbnail
      = image_tag @user.avatar.presence || "default_avatar", class: "user-container__letter-container__individual-letter__user__thumbnail__image"
    .user-container__letter-container__individual-letter__user__info
      .user-container__letter-container__individual-letter__user__info__name
        %h3
          = @user.full_name.presence || "No name"
      .user-container__letter-container__individual-letter__user__info__profile
        %p
          = @user.profile.truncate(15) if @user.profile.present?
  .user-container__letter-container__individual-letter__user-comment
    %p
      = letter.user_comment(@user).content.truncate(50).presence || "No comment"
  .user-container__letter-container__individual-letter__pickers
    - letter.best_five_comments.each do |comment|
      = link_to user_path(comment.user) do
        = image_tag comment.user.avatar.presence || "default_avatar.jpeg", class: "user-container__letter-container__individual-letter__pickers__individual-picker"
  .user-container__letter-container__individual-letter__sub-info
    .user-container__letter-container__individual-letter__sub-info__publisher
      - if letter.site_name.present?
        = letter.site_name.truncate(15)
      - else
        = "No site name"
    .user-container__letter-container__individual-letter__sub-info__time
      - if letter.created_in_24hours?
        = "#{time_ago_in_words(letter.created_at)}前"
      - else
        = letter.created_time

app/views/users/_navbar.html.haml
.user-container__navbar
  .user-container__navbar__box
    - if params[:controller] == "users" && params[:action] == "show"
      .user-container__navbar__box__picks
        %p Picks
    - else
      = link_to user_path(@user), class: "user-container__navbar__box__picks" do
        %p Picks
    - if params[:controller] == "users" && params[:action] == "following"
      .user-container__navbar__box__following-box
        .user-container__navbar__box__following-box__count
          = @user.following.count
        .user-container__navbar__box__following-box__caption
          %p フォロー
    - else
      = link_to following_user_path(@user), class: "user-container__navbar__box__following-box" do
        .user-container__navbar__box__following-box__count
          = @user.following.count
        .user-container__navbar__box__following-box__caption
          %p フォロー
    - if params[:controller] == "users" && params[:action] == "followers"
      .user-container__navbar__box__follower-box
        .user-container__navbar__box__follower-box__count
          = @user.followers.count
        .user-container__navbar__box__follower-box__caption
          %p フォロワー
    - else
      = link_to followers_user_path(@user), class: "user-container__navbar__box__follower-box" do
        .user-container__navbar__box__follower-box__count
          = @user.followers.count
        .user-container__navbar__box__follower-box__caption
          %p フォロワー
    .user-container__navbar__box__follow-box
      - if @user == current_user
      - elsif current_user.following.include?(@user)
        = form_for current_user.with_following(@user), method: :delete do |f|
          = f.submit "フォロー中", class: "user-container__navbar__box__follow-box__btn-blue"
      - else
        = form_tag '/relationships', method: :post do
          = hidden_field_tag :following_id, @user.id
          = submit_tag "フォロー", class: "user-container__navbar__box__follow-box__btn"

app/views/users/_user_info.html.haml
.user-container__user-box
  .user-container__user-box__user
    .user-container__user-box__user__left-info
      = image_tag @user.avatar.presence || "default_avatar.jpeg", class: "user-container__user-box__user__left-info__avatar"
    .user-container__user-box__user__right-info
      .user-container__user-box__user__right-info__name
        - if @user.full_name.present?
          = @user.full_name.truncate(35)
        - else
          No name
      .user-container__user-box__user__right-info__like-count
        %p 総 Like 数: #{@user.sum_like}
      .user-container__user-box__user__right-info__profile
        = @user.profile

app/views/users/edit.html.haml
.container
  .container__setting
    .container__setting__container
      .container__setting__container__title
        アカウント設定
      = form_for(current_user) do |f|
        .container__setting__container__avatar
          .container__setting__container__avatar__label
            アイコン
          .container__setting__container__avatar__cover
            = image_tag current_user.avatar, id: "user-avatar", class: "container__setting__container__avatar__cover__image", id: "avatar_image"
            = f.file_field :avatar, class: "container__setting__container__avatar__cover__field", id: "avatar_file"
            = link_to "変更する", "", class: "container__setting__container__avatar__cover__btn"
        .container__setting__container__name
          .container__setting__container__name__label
            名前
          .container__setting__container__name__field
            = f.text_field :last_name, class: "container__setting__container__name__field__last"
            = f.text_field :first_name, class: "container__setting__container__name__field__first"
        .container__setting__container__profile
          .container__setting__container__profile__label
            プロフィール
          = f.text_area :profile, class: "container__setting__container__profile__field"
        .container__setting__container__edit
          = f.submit "保存する", class: "container__setting__container__edit__btn"
        .container__setting__container__delete
          = link_to "退会する", user_path, method: :delete, class: "container__setting__container__delete__btn"

app/views/users/followers.html.haml
.user-container
  = render partial: "users/user_info"
  = render partial: "users/navbar"
  = render partial: "users/follow"

app/views/users/following.html.haml
.user-container
  = render partial: "users/user_info"
  = render partial: "users/navbar"
  = render partial: "users/follow"

app/views/users/index.html.haml
.container
  = render partial: "layouts/sidebar"
  .container__title-block
    .container__title-block__title
      = image_tag 'pro.png', class: "container__title-block__title__image"
      Pickerのおすすめ本
  .container__user-container
    .container__user-container__cover
      - @users.each do |user|
        .container__user-container__cover__individual
          = link_to user_books_path(user), class: "container__user-container__cover__individual__user-info" do
            = image_tag user.avatar.presence || "default_avatar.jpeg", class: "container__user-container__cover__individual__user-info__image"
            .container__user-container__cover__individual__user-info__right-info
              .container__user-container__cover__individual__user-info__right-info__name
                = user.full_name.presence || "No name"
              .container__user-container__cover__individual__user-info__right-info__profile
                - if user.profile.present?
                  = user.profile.truncate(50)
                - else
                  = "No profile"

app/views/users/show.html.haml
.user-container
  = render partial: "users/user_info", locals: { user: @user }
  = render partial: "users/navbar", locals: { user: @user }
  .user-container__letter-container
    = render partial: "users/letter", collection: @letters, locals: { user: @user }