config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: :show
  resources :users, only: [:index, :show, :edit, :update] do
    resources :books, only: [:index, :show, :new, :create, :destroy] do
      resources :impressions, only: [:create, :destroy]
    end
    resources :storages, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :letters, only: [:index, :show, :create] do
    resources :comments, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  root 'letters#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :impressions, ->{ order("created_at desc") }

  def impression(user)
    Impression.find_by(user_id: user, book_id: self.id)
  end

  def self.search_book(key)
    if key.present?
      Amazon::Ecs.debug = true

      books = Amazon::Ecs.item_search(
        key,
        search_index: 'Books',
        dataType: 'script',
        response_group: 'ItemAttributes, Images',
        country: 'jp',
        power: 'Not kindle'
      )

      search_books = []
      books.items.each do |item|
        book = self.new(
          title: item.get('ItemAttributes/Title'),
          image: item.get('LargeImage/URL'),
          url: item.get('DetailPageURL'),
          author: item.get('ItemAttributes/Author'),
          manufacturer: item.get('ItemAttributes/Manufacturer'),
        )
        search_books.push(book)
      end
      return search_books
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @books = Book.where(user_id: @user)
  end

  def show
    @book = Book.find(params[:id])
    @impression = Impression.new
    @impressions = @book.impressions
  end

  def new
    @search_books = Book.search_book(params[:keyword])
  end

  def create
    book = Book.new(create_params)
    if book.save
      flash[:notice] = ""
      redirect_to user_book_path(current_user, book)
    else
      flash[:alert] = "おすすめ本の投稿に失敗しました。"
      redirect_to :back
    end
  end

  private
    def create_params
      params.require(:book).permit(:title, :image, :url, :author, :manufacturer).merge(user_id: current_user.id)
    end
end

app/views/books/_book_list.html.haml
- if @search_books.present?
  - @search_books.each do |book|
    .container__content__result__book-list__book
      = link_to book.url, class: "container__content__result__book-list__book__link" do
        = image_tag book.image, class: "container__content__result__book-list__book__link__image"
      .container__content__result__book-list__book__right-info
        .container__content__result__book-list__book__right-info__title
          = book.title.truncate(26)
        .container__content__result__book-list__book__right-info__author
          = "#{book.author} (著)"
        .container__content__result__book-list__book__right-info__manufacturer
          = book.manufacturer
      = form_tag user_books_path(current_user), method: :create do
        = hidden_field_tag 'book[title]', book.title
        = hidden_field_tag 'book[image]', book.image
        = hidden_field_tag 'book[url]', book.url
        = hidden_field_tag 'book[author]', book.author
        = hidden_field_tag 'book[manufacturer]', book.manufacturer
        = submit_tag "投稿する", class: "container__content__result__book-list__book__submit"

app/views/books/index.html.haml
.container
  = render partial: "users/user_info", locals: { user: @user }
  = render partial: "users/navbar", locals: { user: @user }
  .container__books-container
    .container__books-container__cover
      - @books.each do |book|
        .container__books-container__cover__individual
          = link_to user_book_path(book.user, book), class: "container__books-container__cover__individual__flame" do
            = image_tag book.image, class: "container__books-container__cover__individual__flame__image"
          .container__books-container__cover__individual__right-info
            = link_to user_book_path(book.user, book) do
              .container__books-container__cover__individual__right-info__title
                = book.title
            .container__books-container__cover__individual__right-info__sub-info
              .container__books-container__cover__individual__right-info__sub-info__author
                = "#{book.author} (著)"
              .container__books-container__cover__individual__right-info__sub-info__manufacturer
                = "#{book.manufacturer} (社)"
            .container__books-container__cover__individual__right-info__user
              = image_tag book.user.avatar, class: "container__books-container__cover__individual__right-info__user__avatar"
              .container__books-container__cover__individual__right-info__user__info
                .container__books-container__cover__individual__right-info__user__info__name
                  = book.user.full_name
                .container__books-container__cover__individual__right-info__user__info__profile
                  = book.user.profile
            .container__books-container__cover__individual__right-info__impression
              - if book.impression(@user).present?
                = book.impression(@user).content
              - else
                = "No impression"

app/views/books/new.html.haml
.container
  .container__content
    .container__content__search-box#search-box
      キーワード検索
      = form_tag( new_user_book_path(current_user), method: :get) do
        = text_field_tag :book, "", id: "book_search", class: "container__content__search-box__form", name: "keyword", placeholder: "キーワードを打ち込んでください。", data: { toggle: "#{new_user_book_path(current_user)}" }
        = submit_tag "検索", class: "container__content__search-box__btn"
    .container__content__result
      検索結果
      .container__content__result__book-list#book-list
        = render partial: "books/book_list"

app/views/books/new.js.erb
$('#book-list').html("<%= j render partial: 'books/book_list' %>");

app/views/books/show.html.haml
.container
  = render partial: "layouts/sidebar"
  .container__book-container
    .container__book-container__book-info
      .container__book-container__book-info__block
        .container__book-container__book-info__block__flame
          = image_tag @book.image, class: "container__book-container__book-info__block__flame__image"
        .container__book-container__book-info__block__right-info
          = link_to @book.title.truncate(23), @book.url, class: "container__book-container__book-info__block__right-info__title"
          .container__book-container__book-info__block__right-info__author
            = "#{@book.author} (著)"
          .container__book-container__book-info__block__right-info__manufacturer
            = "#{@book.manufacturer} (社)"
          .container__book-container__book-info__block__right-info__recommend-user
            = image_tag @book.user.avatar, class: "container__book-container__book-info__block__right-info__recommend-user__avatar"
            .container__book-container__book-info__block__right-info__recommend-user__info
              .container__book-container__book-info__block__right-info__recommend-user__info__name
                = @book.user.full_name.truncate(10)
                = image_tag "pro.png", class: "container__book-container__book-info__block__right-info__recommend-user__info__name__pro"
              .container__book-container__book-info__block__right-info__recommend-user__info__profile
                = @book.user.profile.truncate(58)
          = link_to "購入する(Amazon)", @book.url, class: "container__book-container__book-info__block__right-info__buy", target: "_blank"
    .container__book-container__book-impression
      - if user_signed_in?
        .container__book-container__book-impression__block
          .container__book-container__book-impression__block__cover
            = image_tag current_user.avatar.presence || "default_avatar.jpeg", class: "container__book-container__book-impression__block__cover__avatar"
          .container__book-container__book-impression__block__impression
            = form_for @impression, url: user_book_impressions_path(current_user, @book), method: :create do |f|
              = f.text_area :content, class: "container__book-container__book-impression__block__impression__form", placeholder: "感想を書く（任意）"
              = f.submit "Pick", class: "container__book-container__book-impression__block__impression__pick"
    .container__book-container__impressions
      .container__book-container__impressions__block
        - @impressions.each do |impression|
          .container__book-container__impressions__block__individual
            .container__book-container__impressions__block__individual__user
              .container__book-container__impressions__block__individual__user__cover
                = link_to user_path(impression.user) do
                  = image_tag impression.user.avatar.presence || "default_avatar.jpeg", class: "container__book-container__impressions__block__individual__user__cover__avatar"
              .container__book-container__impressions__block__individual__user__info
                .container__book-container__impressions__block__individual__user__info__name
                  = link_to impression.user.full_name.presence || "No name", user_path(impression.user), class: "container__book-container__impressions__block__individual__user__info__name__font"
                .container__book-container__impressions__block__individual__user__info__created-at
                  = "#{time_ago_in_words impression.created_at}前"
              - if current_user == impression.user
                = link_to "削除", user_book_impression_path(current_user, impression.book, impression), method: :delete, class: "container__book-container__impressions__block__individual__user__destroy"
            .container__book-container__impressions__block__individual__impression
              .container__book-container__impressions__block__individual__impression__content
                = impression.content