config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: :show
  resources :users, only: [:index, :show, :edit, :update] do
    resources :books, only: [:index, :show, :new, :create, :destroy] do
      resources :impressions, only: [:create, :destroy]
    end
    resources :storages, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :letters, only: [:index, :show, :create] do
    resources :comments, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  root 'letters#index'
end

app/models/letter.rb
class Letter < ActiveRecord::Base

  has_many :comments, ->{ order("likes_count desc") }, dependent: :destroy
  has_many :storages

  validates :url, format: URI::regexp(%w(http https))

  scope :with_new_letters, ->{ where(comments_count: 1..Float::INFINITY).order(created_at: :desc).first(9) }
  scope :with_better_letters, ->{ where(created_at: [1.days.ago..Time.now], comments_count: 1..Float::INFINITY).order(comments_count: :desc, created_at: :desc).first(5) }
  scope :classify_letters, ->(category){ where(category: category).order("created_at desc") }

  def self.select_categories
    categories = Hash.new
    keys = ["テクノロジー", "ビジネス", "政治・経済", "金融・マーケット", "キャリア・教育", "スポーツ", "イノベーション"]

    keys.each do |key|
      categories["#{key}"] = self.where(created_at: [7.day.ago..Time.now], comments_count: 1..Float::INFINITY, category: key, confidence: 0.7..Float::INFINITY).order(comments_count: :desc, created_at: :desc).first(3)
    end
    categories
  end

  def created_in_24hours?
    now = Time.now
    if (now - 24 * 60 * 60) <= self.created_at.time && self.created_at.time <= now
      true
    else
      nil
    end
  end

  def created_time
    d = self.created_at
    "#{d.year}年#{d.month}月#{d.day}日"
  end

  def best_five_comments
    comments.first(5)
  end

  def user_comment(user)
    comments.find_by(user_id: user.id)
  end

  def max_like_user
    comment = comments.order("likes_count desc").first(1)[0]
    if comment.nil?
      nil
    else
      User.find(comment.user_id)
    end
  end

  def create_letter
    agent = Mechanize.new
    page = agent.get(self.url)
    elements = page.search('meta')

    letter = {}

    elements.each do |ele|
      property = ele.get_attribute(:property)
      if property == "og:title"
        letter[:title] = ele.get_attribute(:content)
      elsif property == "og:image"
        letter[:image] = ele.get_attribute(:content)
      elsif property == "og:site_name"
        letter[:site_name] = ele.get_attribute(:content)
      elsif property == "og:description"
        letter[:description] = ele.get_attribute(:content)
      end
    end
    if letter[:description].present?
      description = letter[:description]
      letter[:category], letter[:confidence] = watson_api(description)
    end
    self.update(letter)
  end

  private
    def watson_api(text)
      uri = URI.parse("https://gateway.watsonplatform.net/natural-language-classifier/api/v1/classifiers/#{ENV['NLC_CLASSIFIER_ID']}/classify")
      params = { text: text }
      uri.query = URI.encode_www_form(params)

      request = Net::HTTP::Get.new(uri)
      request.basic_auth( ENV['NLC_USERNAME'], ENV['NLC_PASSWORD'])

      response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == "https"){|http|
        http.request(request);
      }

      obj = JSON.parse(response.body)
      if (obj["top_class"] || obj["classes"]).nil?
        return "", 0
      else
        return obj["top_class"], (obj["classes"][0]["confidence"])
      end
    end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def index
    @letters = Letter.with_new_letters
    @better_letters = Letter.with_better_letters
    @categories = Letter.select_categories
  end

  def new
  end

  def create
    @letters = Letter.order("created_at desc")
    unless @letters.pluck(:url).include?(url_params[:url])
      letter = Letter.new(url_params)
      if letter.save
        letter.create_letter
        flash[:notice] = ""
        redirect_to letter_path(letter)
      else
        flash[:alert] = "投稿に失敗しました。"
        redirect_to :back
      end
    else
      @select_letter = Letter.find_by(url: url_params[:url])
      redirect_to letter_path(@select_letter)
    end
  end

  def show
    @letter = Letter.find(params[:id])
    @comments = @letter.comments
    @comment = Comment.new
    @create_storage = Storage.new
    @delete_storage = Storage.find_by(user_id: current_user.id, letter_id: @letter)
  end

  private
    def url_params
      params.permit(:url)
    end
end

app/views/letters/_category.html.haml
.category-container
  - @categories.each do |key, categories|
    - if categories.present?
      .category-container__category-individual
        .category-container__category-individual__title-block
          .category-container__category-individual__title-block__title
            = key
          = link_to "#{key}\t一覧を見る", category_path(key), class: "category-container__category-individual__title-block__to-list"
        = render partial: "letters/letter", collection: categories

app/views/letters/_letter.html.haml
- unless letter.max_like_user.nil?
  .container__letter-container__letter-block__individual-letter
    .container__letter-container__letter-block__individual-letter__thumbnail
      = link_to letter_path(letter) do
        = image_tag letter.image.presence || "default_letter_image.jpg", class: "container__letter-container__letter-block__individual-letter__thumbnail__image"
        .container__letter-container__letter-block__individual-letter__thumbnail__picks-box
          .container__letter-container__letter-block__individual-letter__thumbnail__picks-box__cover
            .container__letter-container__letter-block__individual-letter__thumbnail__picks-box__cover__size
              = letter.comments_count
            .container__letter-container__letter-block__individual-letter__thumbnail__picks-box__cover__picks
              Picks
    .container__letter-container__letter-block__individual-letter__title
      %h2
        = link_to letter.title.truncate(28).presence || "No title", letter_path(letter), class: "container__letter-container__letter-block__individual-letter__title__font"
    = link_to user_path(letter.max_like_user), class: "container__letter-container__letter-block__individual-letter__user" do
      .container__letter-container__letter-block__individual-letter__user__thumbnail
        = image_tag letter.max_like_user.avatar.presence || "default_avatar.jpeg", class: "container__letter-container__letter-block__individual-letter__user__thumbnail__image"
      .container__letter-container__letter-block__individual-letter__user__info
        .container__letter-container__letter-block__individual-letter__user__info__name
          %h3
            = letter.max_like_user.full_name.presence || "No name"
        .container__letter-container__letter-block__individual-letter__user__info__profile
          %p
            = letter.max_like_user.profile.truncate(15) if letter.max_like_user.profile.present?
    = link_to letter_path(letter), class: "container__letter-container__letter-block__individual-letter__user-comment" do
      %p
        = letter.user_comment(letter.max_like_user).content.truncate(53).presence || "No comment"
    .container__letter-container__letter-block__individual-letter__pickers
      - if letter.comments.length > 0
        - letter.best_five_comments.each do |comment|
          = link_to user_path(comment.user) do
            = image_tag comment.user.avatar.presence || "default_avatar.jpeg", class: "container__letter-container__letter-block__individual-letter__pickers__individual-picker"
    .container__letter-container__letter-block__individual-letter__sub-info
      .container__letter-container__letter-block__individual-letter__sub-info__publisher
        - if letter.site_name.present?
          = letter.site_name.truncate(12)
        - else
          = "No site name"
      .container__letter-container__letter-block__individual-letter__sub-info__time
        - if letter.created_in_24hours?
          = "#{time_ago_in_words(letter.created_at)}前"
        - else
          = letter.created_time

app/views/letters/_like_btn.html.haml
- if user_signed_in?
  = link_to letter_comment_likes_path(@letter, comment), controller: :likes, method: :post, class: "container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link", remote: true do
    .container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link__likes-count
      = comment.likes.length
    .container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link__likes
      Likes
- else
  = link_to letter_comment_likes_path(@letter, comment), controller: :likes, method: :post, class: "container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link" do
    .container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link__likes-count
      = comment.likes.length
    .container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link__likes
      Likes

app/views/letters/_like_btn_red.html.haml
= link_to letter_comment_like_path(@letter, comment, comment.user_like(current_user)), controller: :likes, method: :delete, class: "container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link", remote: true do
  .container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link__likes-count-red
    = comment.likes.length
  .container__contents-container__news-comment__comments__individual__comment__like-container__like-panel__like-link__likes-red
    Likes

app/views/letters/_new_modal.html.haml
.modal#letter-new-modal
  .modal__back
  .modal__pick-form
    .modal__pick-form__message
      %p URLを入力して
      %p おすすめの記事を投稿しましょう
    = form_tag('/letters') do |f|
      .modal__pick-form__url-group
        = text_field_tag :url, "", placeholder: "URLを入力", class: "modal__pick-form__url-group__url-value", id: "letter-form", autofocus: true

app/views/letters/_storage_btn.html.haml
= form_for([current_user, @create_storage]) do |f|
  = f.hidden_field :letter_id, value: @letter.id
  = f.submit "保管する", class: "container__contents-container__contents-area__meta__storage__normal-btn"

app/views/letters/_storage_btn_red.html.haml
= link_to "保管中", user_storage_path(current_user, @delete_storage), class: "container__contents-container__contents-area__meta__storage__red-btn", controller: :storages, method: :delete

app/views/letters/_topics.html.haml
- if @better_letters.length >= 2
  .container__topics
    .container__topics__flame
      .container__topics__flame__main-flame
        %ul.bxslider
          - @better_letters.each do |letter|
            %li
              = link_to letter_path(letter), class: "container__topics__flame__main-flame__link" do
                = image_tag letter.image, class: "container__topics__flame__main-flame__link__image"
                .container__topics__flame__main-flame__link__block
                  .container__topics__flame__main-flame__link__block__picks-box
                    .container__topics__flame__main-flame__link__block__picks-box__cover
                      .container__topics__flame__main-flame__link__block__picks-box__cover__size
                        = letter.comments_count
                      .container__topics__flame__main-flame__link__block__picks-box__cover__picks
                        Picks
                  .container__topics__flame__main-flame__link__block__title
                    - if letter.title.present?
                      = letter.title.truncate(40)
                    - else
                      = "No title"
                  .container__topics__flame__main-flame__link__block__sub-info
                    .container__topics__flame__main-flame__link__block__sub-info__publisher
                      - if letter.site_name.present?
                        = letter.site_name.truncate(20)
                      - else
                        = "No site name"
                    .container__topics__flame__main-flame__link__block__sub-info__time
                      - if letter.created_in_24hours?
                        = "#{time_ago_in_words(letter.created_at)}前"
                      - else
                        = letter.created_time
      .container__topics__flame__sub-flame
        = link_to letter_path(@better_letters[0]), class: "container__topics__flame__sub-flame__first" do
          = image_tag @better_letters[0].image.presence || "default_letter_image.jpg", class: "container__topics__flame__sub-flame__first__image"
          .container__topics__flame__sub-flame__first__title
            - if @better_letters[0].title.present?
              = @better_letters[0].title.truncate(40)
            - else
              = "No title"
        = link_to letter_path(@better_letters[1]), class: "container__topics__flame__sub-flame__second" do
          = image_tag @better_letters[1].image.presence || "default_letter_image.jpg", class: "container__topics__flame__sub-flame__second__image"
          .container__topics__flame__sub-flame__second__title
            - if @better_letters[1].title.present?
              = @better_letters[1].title.truncate(40)
            - else
              = "No title"

app/views/letters/index.html.haml
.container
  = render partial: "layouts/sidebar"
  = render partial: "letters/topics"
  .container__letter-container
    .container__letter-container__letter-block
      = render @letters
      = render partial: "letters/category"

app/views/letters/show.html.haml
.container
  = render partial: "layouts/sidebar"
  .container__cover
    .container__cover__letter-title-box
      = link_to "← 総合トップ", root_path, class: "container__cover__letter-title-box__title"
  .container__contents-container
    .container__contents-container__contents-area
      .container__contents-container__contents-area__letter-image
        = link_to @letter.url, target: "_blank" do
          = image_tag @letter.image.presence || "default_letter_image.jpg", class: "container__contents-container__contents-area__letter-image__thumbnail"
          .container__contents-container__contents-area__letter-image__picks-box
            .container__contents-container__contents-area__letter-image__picks-box__cover
              .container__contents-container__contents-area__letter-image__picks-box__cover__size
                = @letter.comments.length
              .container__contents-container__contents-area__letter-image__picks-box__cover__picks
                Picks
      .container__contents-container__contents-area__letter-title
        = link_to @letter.title.truncate(40).presence || "No title", @letter.url, class: "container__contents-container__contents-area__letter-title__font", target: "_blank"
      .container__contents-container__contents-area__meta
        .container__contents-container__contents-area__meta__site-name
          = @letter.site_name.truncate(12).presence || "No site name"
        .container__contents-container__contents-area__meta__time-ago
          = "#{time_ago_in_words(@letter.created_at)}前"
        .container__contents-container__contents-area__meta__storage
          - if user_signed_in?
            - unless current_user.storage_letters.include?(@letter)
              = render partial: "letters/storage_btn"
            - else
              = render partial: "letters/storage_btn_red"
      .container__contents-container__contents-area__read-more
        = link_to "続きを読む", @letter.url, class: "container__contents-container__contents-area__read-more__btn", target: "_blank"

    .container__contents-container__news-comment
      - if user_signed_in? && @letter.user_comment(current_user).nil?
        .container__contents-container__news-comment__pick-editor
          .container__contents-container__news-comment__pick-editor__cover
            = image_tag current_user.avatar.presence || "default_avatar.jpeg", class: "container__contents-container__news-comment__pick-editor__cover__avatar"
          = form_for [@letter, @comment] ,method: :create do |f|
            .container__contents-container__news-comment__pick-editor__comment
              = f.text_area :content, class: "container__contents-container__news-comment__pick-editor__comment__form", placeholder: "コメントを書く（任意）"
            .container__contents-container__news-comment__pick-editor__pick
              = f.submit "Pick", class: "container__contents-container__news-comment__pick-editor__pick__btn"
      .container__contents-container__news-comment__comments
        - @comments.each do |comment|
          .container__contents-container__news-comment__comments__individual
            .container__contents-container__news-comment__comments__individual__user
              .container__contents-container__news-comment__comments__individual__user__cover
                = link_to user_path(comment.user) do
                  = image_tag comment.user.avatar.presence || "default_avatar.jpeg", class: "container__contents-container__news-comment__comments__individual__user__cover__avatar"
              .container__contents-container__news-comment__comments__individual__user__info
                .container__contents-container__news-comment__comments__individual__user__info__name
                  = link_to comment.user.full_name.presence || "No name", user_path(comment.user), class: "container__contents-container__news-comment__comments__individual__user__info__name__font"
                .container__contents-container__news-comment__comments__individual__user__info__created-at
                  = time_ago_in_words comment.created_at
                - if current_user == comment.user
                  = link_to "削除", letter_comment_path(@letter, comment), method: :delete, class: "container__contents-container__news-comment__comments__individual__user__info__destroy", id: "comment-edit-btn"
            .container__contents-container__news-comment__comments__individual__comment
              .container__contents-container__news-comment__comments__individual__comment__content
                = comment.content
              .container__contents-container__news-comment__comments__individual__comment__like-container
                .container__contents-container__news-comment__comments__individual__comment__like-container__contents-container__like-panel{id: "like-btn-#{comment.id}"}
                  - if user_signed_in?
                    - unless comment.likes.exists?(user_id: current_user.id)
                      = render partial: "letters/like_btn", locals: { comment: comment }
                    - else
                      = render partial: "letters/like_btn_red", locals: { comment: comment }
                  - else
                    = render partial: "letters/like_btn", locals: { comment: comment }