config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: :show
  resources :users, only: [:index, :show, :edit, :update] do
    resources :books, only: [:index, :show, :new, :create, :destroy] do
      resources :impressions, only: [:create, :destroy]
    end
    resources :storages, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :letters, only: [:index, :show, :create] do
    resources :comments, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end
  root 'letters#index'
end

app/views/layouts/_footer.html.haml
.footer
  .footer__copyright &copy; News Pipicks 2016.

app/views/layouts/_header.html.haml
.header
  = link_to root_path, class: "header__title" do
    = image_tag "title_logo.png", class: "header__title__logo"

  .header__nav
    - if user_signed_in?
      .header__nav__user#user-header-image
        = image_tag current_user.avatar.presence || "default_avatar.jpeg", class: "header__nav__user__avatar"
      = image_tag "book.png", class: "header__nav__user-index", id: "books"
      = image_tag "flag.png", class: "header__nav__user-storage", id: "user-storages"
      = image_tag "pen.png", class: "header__nav__new-letter", id: "letter-new"
    - else
      .header__nav__regist
        = link_to "無料登録", new_user_registration_path, class: "header__nav__regist__font"
      .header__nav__login
        = link_to "ログイン", new_user_session_path, class: "header__nav__login__font"
- if user_signed_in?
  .user#user-back
    .user__back#user-back-close
      .user__back__user-menu#user-menu-container
        .user__back__user-menu__user-name
          = link_to current_user.full_name.presence || "No name", user_path(current_user), class: "user__back__user-menu__user-name__font"
        .user__back__user-menu__user-edit
          = link_to "設定", edit_user_path(current_user), class: "user__back__user-menu__user-edit__font"
        .user__back__user-menu__logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "user__back__user-menu__logout__font"

  .book#books-back
    .book__back#books-back-close
      .book__back__book-menu#books-menu-container
        = link_to users_path, class: "book__back__book-menu__books-path" do
          = image_tag "pro.png", class: "book__back__book-menu__books-path__image"
          .book__back__book-menu__books-path__sentence
            Pickerのおすすめ本
        = link_to "おすすめ本の投稿", new_user_book_path(current_user), class: "book__back__book-menu__posting-book"

  .storage#storage-back
    .storage__back#storage-back-close
      .storage__back__storage-menu#storage-letters
        - if current_user.storage_letters.present?
          - current_user.storages.each do |storage|
            = link_to letter_path(storage.letter), class: "storage__back__storage-menu__link" do
              = image_tag storage.letter.image, class: "storage__back__storage-menu__link__image"
              .storage__back__storage-menu__link__right-block
                .storage__back__storage-menu__link__right-block__title
                  = storage.letter.title.truncate(40).presence || "No name"
                .storage__back__storage-menu__link__right-block__time
                  = "#{time_ago_in_words(storage.created_at)}前"

  = render partial: "letters/new_modal"

app/views/layouts/_sidebar.html.haml
- if user_signed_in?
  .container__user-area
    = link_to user_path(current_user), class: "container__user-area__user" do
      .container__user-area__user__thumbnail
        = image_tag current_user.avatar.presence || "default_avatar.jpeg", class: "container__user-area__user__thumbnail__avatar"
      .container__user-area__user__name
        .container__user-area__user__name__font
          = current_user.full_name.presence || "名前を登録下さい"
    .container__user-area__follow-info
      = link_to following_user_path(current_user), class: "container__user-area__follow-info__following" do
        .container__user-area__follow-info__following__count
          = current_user.following.count
        .container__user-area__follow-info__following__caption
          %p フォロー
      = link_to followers_user_path(current_user), class: "container__user-area__follow-info__follower" do
        .container__user-area__follow-info__follower__count
          = current_user.followers.count
        .container__user-area__follow-info__follower__caption
          %p フォロワー
- else
  .container__user-area
    .container__user-area__user
      .container__user-area__user__thumbnail
        = link_to new_user_registration_path do
          = image_tag "default_avatar.jpeg", class: "container__user-area__user__thumbnail__avatar"
      .container__user-area__user__name
        %h2
          = link_to new_user_registration_path, class: "container__user-area__user__name__font" do
            = "アカウント登録下さい"
    .container__user-area__follow-info
      = link_to new_user_registration_path, class: "container__user-area__follow-info__following" do
        .container__user-area__follow-info__following__count
          = "-"
        .container__user-area__follow-info__following__caption
          %p フォロー
      = link_to new_user_registration_path, class: "container__user-area__follow-info__follower" do
        .container__user-area__follow-info__follower__count
          = "-"
        .container__user-area__follow-info__follower__caption
          %p フォロワー

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NewsPipicks
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
    = javascript_include_tag  "//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
    = javascript_include_tag  "jquery.bxslider.min.js"
    = javascript_include_tag  "jquery.autosize.min.js"
    = stylesheet_link_tag     "jquery.bxslider.css", rel: "stylesheet"
  %body
    = render partial: 'layouts/header'
    - flash.each do |type, msg|
      - if type == "notice" && msg.blank?
        = image_tag "logo.png", id: "logo"
      - else
        %div{class: "#{type}", id: "flash"}
          = msg
    = yield
    = render partial: 'layouts/footer'